Links\LinksBundle\Entity\Links:
    type: entity
    table: links
    id:
        id:
            type: integer
            generator: {strategy: AUTO}
        id_user:
            type: integer
    fields:
        url:
            type: string
            length: 30
            unique: true
        clicks:
            type: integer
        is_active:
            type: bool
            nullable: false
    manyToOne:
        fos_user_user:
            targetEntity: User
                joinColumn:
                  name: id_user
                  referencedColumnName: id